export const dosenDb = [
  {
    name: 'Admin',
    username: '121314151617181910',
    password: 'admin',
    job: 'admin',
    access: 'admin',
  },
  {
    name: 'pa eril',
    username: '111111',
    password: '111111',
    job: 'dosen',
    access: 'dosen/tendik',
    permintaanBimbingan: [],
    bimbingan: [],
  },
  {
    name: 'pa opik',
    username: '222222',
    password: '222222',
    access: 'dosen/tendik',
    job: 'dosen',
  },
  {
    name: 'pa megi',
    username: '333333',
    password: '333333',
    access: 'dosen/tendik',
    job: 'dosen',
  },
  {
    name: 'pa teguh',
    username: '444444',
    password: '444444',
    access: 'dosen/tendik',
    job: 'dosen',
  },
  {
    name: 'pa bagja',
    username: '555555',
    password: '555555',
    access: 'dosen/tendik',
    job: 'dosen',
  },
  {
    name: 'pa dede',
    username: '666666',
    password: '666666',
    access: 'dosen/tendik',
    job: 'tendik',
  },
]